export interface DestinyResult {
  quote: string;
  reading: string;
}

export const quotes: DestinyResult[] = [
  { quote: "The sea does not wait for the drowning man to learn to swim.", reading: "Nature is indifferent to your current crisis. You must adapt immediately or be swept under by the tides of change." },
  { quote: "A heavy shadow is cast only by a brilliant light.", reading: "The darkness you feel today is proportional to the greatness you are capable of. Do not fear the depth of your own complexity." },
  { quote: "The mountain is highest when viewed from the valley floor.", reading: "Your current perspective makes your obstacles look impossible. You are currently standing too low to see the path up." },
  { quote: "Silence is the only truth that cannot be misquoted.", reading: "You are speaking too much and listening too little. The answers you seek are hiding in the quiet gaps of your routine." },
  { quote: "The fire you ignite today may keep you warm but it will also turn to ash.", reading: "Enjoy the current spark but remember that temporary comforts always consume themselves. Prepare for the cold that follows." },
  { quote: "A bird born in a cage thinks flying is a sickness.", reading: "You have been restricted for so long that freedom actually feels dangerous to you. It is time to challenge your perceived limits." },
  { quote: "The loudest room is often the emptiest.", reading: "You are surrounding yourself with noise to avoid the vacuum in your own heart. Sit alone and see what remains." },
  { quote: "Rivers carve through stone not with strength but with time.", reading: "Your immediate aggression is failing. Apply gentle, consistent pressure instead, and the hardest obstacle will eventually yield." },
  { quote: "A locked door is merely a wall until you find the key.", reading: "The barrier you face is only permanent because you are using the wrong tools. Stop pushing and start searching for the mechanism." },
  { quote: "The moon does not apologize for its phases.", reading: "You are constantly hiding your inconsistencies to please others. Accept that you are meant to change, to wax and to wane." },
  { quote: "A full cup is useless for anything but spilling.", reading: "You are too certain of your own wisdom to learn anything new. Empty your mind of what you think you know." },
  { quote: "Shadows only grow longer when the sun is setting.", reading: "The problems you are hyper-focusing on are symptoms of a cycle coming to an end. Prepare for the night." },
  { quote: "The archer must pull the string back to shoot the arrow forward.", reading: "Your recent regressions are not failures. You are currently in the tension phase of a massive breakthrough." },
  { quote: "Even the sharpest blade cannot cut its own handle.", reading: "You are trying to fix a problem that you yourself have created. You need an external perspective to move forward." },
  { quote: "The desert is only a desert to those who have never seen the rain.", reading: "Your current scarcity is blinding you to the abundance that is coming. Do not let the dry season define your soul." },
  { quote: "A mirror shows the face but breaks at the touch of the soul.", reading: "You are obsessing over appearances while your internal foundation is cracking. Stop looking at the surface." },
  { quote: "The tree that refuses to bend will snap in the storm.", reading: "Your current rigidity is your greatest weakness. If you do not learn to compromise, the world will break you." },
  { quote: "Gold is tested in fire, but humans are tested by other humans.", reading: "A difficult relationship in your life right now is not meant to break you, but to refine your character." },
  { quote: "A ship in harbor is safe, but that is not what ships are for.", reading: "You are choosing safety over purpose. The waves are high, but staying docked will rot your spirit." },
  { quote: "The grave is full of unsaid words and unfinished plans.", reading: "Stop waiting for the 'right time' to speak or act. The machine only gives you one card per day; spend it wisely." },
  { quote: "No one watches the sun set while looking east.", reading: "You are so focused on your past that you are missing the beauty of the endings happening right now." },
  { quote: "A borrowed lantern casts no heat.", reading: "You are living off the energy and ideas of others. It is time to find your own source of light." },
  { quote: "The mountain does not care if you choose to climb it or not.", reading: "Reality is indifferent to your ambitions. The work is there. It doesn't matter if you complain or celebrate." },
  { quote: "Even a broken clock is right twice a day.", reading: "Do not dismiss the advice of those you dislike. Even a fool can stumble into the truth occasionally." },
  { quote: "You cannot navigate an ocean by staring at the wake.", reading: "Stop analyzing what has already happened. The water is already gone. Look toward the horizon." },
  { quote: "A house built on sand cannot blame the weather.", reading: "Your current instability is a result of poor foundations, not bad luck. Rebuild from the ground up." },
  { quote: "The silence between notes is what makes the music.", reading: "Do not fear the pauses and delays in your life. They provide the rhythm that makes the active parts meaningful." },
  { quote: "A mask worn too long becomes the face.", reading: "You have been pretending to be someone else for so long that you are losing your original self. Take it off before it's permanent." },
  { quote: "The tallest tree catches the most wind.", reading: "Your recent rise to prominence has brought criticism. Do not take it personally; it is simply the nature of heights." },
  { quote: "The river remembers the source even as it enters the sea.", reading: "You are forgetting where you came from. Success is turning you into someone unrecognizable. Remember your roots." },
  { quote: "A seed does not see the forest while it is buried in the dirt.", reading: "Your current struggle feels like burial, but it is actually planting. Trust the dark process of growth." },
  { quote: "The road to hell is paved with good intentions.", reading: "Your kindness is becoming a liability. You are enabling someone who needs to learn their own lessons." },
  { quote: "A blunt axe makes for a long day.", reading: "You are working too hard and thinking too little. Stop. Sharpen your skills. Then continue." },
  { quote: "The horizon is an illusion that recedes as you approach.", reading: "Stop chasing a final destination. There is no 'there.' There is only the walk." },
  { quote: "Every ending is a new beginning in disguise.", reading: "Do not mourn what is passing. The space being cleared is exactly what you need for your next phase." },
  { quote: "A fool admires the fruit, but a wise man tends the roots.", reading: "Stop obsessing over the results. Focus on your daily inputs, and the fruit will take care of itself." },
  { quote: "The stone in the shoe ruins the finest boots.", reading: "Ignore the small irritations today and they will become a blister tomorrow. Address the small things immediately." },
  { quote: "You cannot steer a parked car.", reading: "Stop over-planning and start moving. You can only correct your course once you have momentum." },
  { quote: "A golden cage is still a cage.", reading: "Do not be fooled by the luxury of your current situation. If you have no freedom, you are still a prisoner." },
  { quote: "The archer's target is himself.", reading: "The obstacles you see in the world are reflections of your own internal conflicts. Fix the internal, and the target will fall." },
  { quote: "A ship doesn't sink because of the water around it, but because of the water in it.", reading: "The chaos of the world cannot hurt you unless you let it into your mind. Seal the leaks." },
  { quote: "The morning sun doesn't know what happened last night.", reading: "Every day is a clean slate. Do not carry the weight of yesterday's mistakes into today's light." },
  { quote: "A thousand-mile journey starts with a single step.", reading: "Stop looking at the mountain. Just look at your feet. Take the first step today." },
  { quote: "The spider's web is a fortress to the spider and a trap to the fly.", reading: "Your perspective determines your reality. What you see as a safety net, others see as a limitation." },
  { quote: "A small spark can burn down a great forest.", reading: "Be careful with your words today. A tiny bit of negativity could escalate into a major conflict." },
  { quote: "The moon reflects the sun but creates its own mystery.", reading: "It is okay to learn from masters, but ensure you add your own unique essence to everything you do." },
  { quote: "A bridge built for everyone eventually collapses under the weight.", reading: "Stop trying to be everything to everyone. You are spread too thin and your integrity is failing." },
  { quote: "The eagle does not hunt flies.", reading: "You are wasting your massive potential on trivial drama. Raise your sights and focus on higher goals." },
  { quote: "A well that is never used eventually dries up.", reading: "Your talents are stagnating because you are too afraid to use them. Activity is the only way to keep the flow alive." },
  { quote: "The longest day eventually meets the night.", reading: "Your current period of intense activity is coming to an end. Prepare for rest. You have earned it." }
];
