export interface DestinyResult {
  quote: string;
  reading: string;
}

export const quotes: DestinyResult[] = [
{ quote: "The quietest rooms hold the loudest memories.", reading: "Your past is catching up to you today, but it brings lessons, not regrets. Listen to it closely." },
  { quote: "You cannot outrun the rain, but you can choose to walk in it.", reading: "A minor hardship is approaching. Do not waste energy fighting the inevitable. Acceptance is your strongest shield." },
  { quote: "Not every closed door is locked.", reading: "An opportunity you thought was gone is resting quietly. All you need to do is turn the handle one more time." },
  { quote: "A seed grows in darkness before it sees the sun.", reading: "You may feel isolated right now, but this period of quiet is necessary for your next phase of growth." },
  { quote: "The mountain does not care if you are tired.", reading: "The world will not stop for your exhaustion. Pace yourself, gather your strength, and keep climbing." },
  { quote: "Some fires burn only to clear the forest floor.", reading: "A recent loss or failure was necessary. It created the space required for something new to take root." },
  { quote: "Even the sharpest blade rests in its sheath.", reading: "You have been fighting battles that do not belong to you. It is time to step back and preserve your energy." },
  { quote: "The river cuts through rock by persistence, not by force.", reading: "Patience will serve you better than aggression today. Keep pushing gently and the obstacle will yield." },
  { quote: "A heavy coat provides no comfort in the summer.", reading: "You are carrying burdens from a season you have already survived. It is time to let them drop." },
  { quote: "No one watches the sun set while looking east.", reading: "You are missing the beauty of your current reality because you are too focused on what you left behind." },
  { quote: "The fastest runner still crosses the same finish line.", reading: "Stop comparing your pace to others. Your journey takes exactly as long as it needs to." },
  { quote: "A house built on sand shifting will always feel unsettled.", reading: "Examine your foundations today. Some of the principles you are relying on may need to be rebuilt." },
  { quote: "You cannot navigate the ocean if you refuse to leave the shore.", reading: "Safety provides comfort but denies adventure. It is time to take a calculated risk." },
  { quote: "An anchor holds the ship, but it also sinks it.", reading: "Something keeping you secure is also holding you down. Evaluate what you are truly afraid of losing." },
  { quote: "Mirrors show the face, not the character.", reading: "Do not judge your progress by external appearances. Your deepest changes are invisible to the eye." },
  { quote: "The loudest voice in the room often has the least to say.", reading: "Do not be swayed by confident arrogance today. Trust the quiet intuition guiding you from within." },
  { quote: "A rusted key will never turn the lock.", reading: "Stop applying old solutions to new problems. You must adapt your approach if you want to move forward." },
  { quote: "Storms do not last forever, but their damage can.", reading: "Be careful with your words during times of anger. You will survive the conflict, but relationships may not." },
  { quote: "The horizon moves no matter how fast you run.", reading: "Stop chasing perfection. There will always be another goal. Learn to sit down and appreciate the present." },
  { quote: "A full cup cannot receive more water.", reading: "Your stubbornness is blocking new wisdom. Empty your mind of what you think you know." },
  { quote: "You look at the stars but forget the earth beneath your feet.", reading: "Your grand dreams are noble, but you are neglecting the practical steps required to build them." },
  { quote: "A bird born in a cage thinks flying is an illness.", reading: "You have grown too accustomed to your limitations. Challenge them today." },
  { quote: "The fire that warms can also burn.", reading: "A passion or relationship you are pursuing is becoming dangerous. Monitor your boundaries closely." },
  { quote: "Shadows only exist where there is light.", reading: "The darkness you are feeling right now is proof that hope is nearby. Turn toward the source." },
  { quote: "A borrowed lantern casts no warmth.", reading: "Stop relying on the success or energy of others to carry you. You must light your own way." },
  { quote: "The oak fought the wind and was broken, the willow bent and survived.", reading: "Flexibility is your greatest asset right now. Do not be rigid in your expectations." },
  { quote: "You cannot write a new chapter while reading the old one.", reading: "It is time to close the book on a past relationship or failure. The ink is dry." },
  { quote: "A blunt axe makes for a long day.", reading: "Take time to rest and sharpen your skills. Brute force will simply exhaust you without yielding a result." },
  { quote: "The map is not the territory.", reading: "Your strict plans are about to fail. Stay alert and navigate by the terrain you actually see, not what you expected to see." },
  { quote: "A thief cannot steal an empty purse.", reading: "You are worrying about losing things that hold no real value. Let go of material anxieties." },
  { quote: "The silence between notes makes the music.", reading: "Do not fear the pauses in your life. Stillness is where the meaning is created." },
  { quote: "A ship in harbor is safe, but that is not what ships are for.", reading: "You are avoiding conflict to keep the peace. It is time to sail out and face the waves." },
  { quote: "We suffer more often in imagination than in reality.", reading: "Your anxiety is lying to you. The disaster you are picturing will not come to pass in the way you fear." },
  { quote: "A fool admires the fruit, a wise person tends the roots.", reading: "Stop obsessing over the final outcome. Focus on your daily habits and the results will naturally follow." },
  { quote: "The moon does not apologize to the night for its shine.", reading: "Stop making yourself smaller to make others feel comfortable. Be brilliant and let them adjust." },
  { quote: "A falling leaf feels no sense of tragedy.", reading: "Accept endings as a natural part of the cycle. Do not grieve what is simply making way for the spring." },
  { quote: "The well runs dry if it is never given time to rain.", reading: "You are giving too much of yourself to others. It is time to refill your own reserves." },
  { quote: "A mask worn too long becomes the face.", reading: "You are pretending to be someone you are not to fit in. Drop the act before you forget who you really are." },
  { quote: "The longest journey is the journey inward.", reading: "You are seeking external validation for an internal problem. Sit alone and ask yourself the hard questions." },
  { quote: "A bridge cannot be built from one side only.", reading: "A conflict in your life requires mutual effort to resolve. If they will not build, you must walk away." },
  { quote: "The tallest tree catches the most wind.", reading: "Your recent success will attract criticism. Stand firm and let the wind howl." },
  { quote: "A golden cage is still a cage.", reading: "Do not let comfort trap you in a situation that drains your soul. Freedom is worth the risk of struggle." },
  { quote: "The archer must pull backward to shoot forward.", reading: "A recent setback is not a failure. You are gathering tension for a massive leap forward." },
  { quote: "A stone in the shoe ruins the finest boots.", reading: "Pay attention to small irritations today. If ignored, they will blister and stop your progress entirely." },
  { quote: "The desert teaches you the value of a single drop.", reading: "This period of scarcity is temporary, but it is meant to teach you gratitude for what you once took for granted." },
  { quote: "A clock that has stopped is right twice a day.", reading: "Even bad advice can contain a sliver of truth. Listen carefully to your critics today." },
  { quote: "The ocean does not bargain with the shore.", reading: "There are forces at play bigger than your control. Yield to the tide and float rather than drowning." },
  { quote: "A spark ignored can burn down a city.", reading: "A minor detail you are glossing over will snowball into a disaster. Address it immediately." },
  { quote: "You cannot steer a parked car.", reading: "Stop waiting for the perfect direction to appear. Pick a path and start moving so you can correct your course." },
  { quote: "The grave is full of unsaid words.", reading: "Do not wait for the perfect moment to tell someone how you feel. Speak your truth today." },
  { quote: "A star finds the quiet growth.", reading: "You have been avoiding create a lasting impact." },
  { quote: "The forest holds the passing storm.", reading: "You have been avoiding offer a fresh start." },
  { quote: "A bird breaks the path forward.", reading: "You have been avoiding offer a fresh start." },
  { quote: "The forest carries the heavy heart.", reading: "A familiar face redefine your priorities." },
  { quote: "The moon carries the secret joy.", reading: "Your efforts are offer a fresh start." },
  { quote: "The moon observes the path forward.", reading: "An unexpected turn restore your balance." },
  { quote: "A key remembers the weight of time.", reading: "Your efforts are offer a fresh start." },
  { quote: "A gate guides the distant future.", reading: "A discovery is near. restore your balance." },
  { quote: "A key forgets the quiet growth.", reading: "A discovery is near. redefine your priorities." },
  { quote: "The stone speaks to the final answer.", reading: "A decision will soon lead to a unexpected success." },
  { quote: "A bird guides the passing storm.", reading: "A decision will soon challenge your beliefs." },
  { quote: "The stone speaks to the deep memory.", reading: "The path you choose offer a fresh start." },
  { quote: "A gate reveals the hidden strength.", reading: "You have been avoiding challenge your beliefs." },
  { quote: "A seed forgets the rising tide.", reading: "You have been avoiding bring long awaited clarity." },
  { quote: "The ocean waits for the clear vision.", reading: "A decision will soon change everything." },
  { quote: "A leaf forgets the rising tide.", reading: "Your strength is test your patience." },
  { quote: "A candle speaks to the deep memory.", reading: "The current phase challenge your beliefs." },
  { quote: "A mountain waits for the secret joy.", reading: "A discovery is near. challenge your beliefs." },
  { quote: "A candle waits for the unspoken promise.", reading: "An unexpected turn redefine your priorities." },
  { quote: "The fire forgets the rising tide.", reading: "A quiet moment open a new door." },
  { quote: "The moon seeks the shifting light.", reading: "A familiar face redefine your priorities." },
  { quote: "A gate seeks the path forward.", reading: "A familiar face test your patience." },
  { quote: "The fire reflects the final answer.", reading: "A familiar face change everything." },
  { quote: "The wind finds the rising tide.", reading: "A familiar face bring long awaited clarity." },
  { quote: "A bridge holds the secret joy.", reading: "A reunion will bring reveal your true nature." },
  { quote: "The wheel holds the distant future.", reading: "A reunion will bring open a new door." },
  { quote: "The sky holds the final answer.", reading: "The path you choose open a new door." },
  { quote: "The root breaks the clear vision.", reading: "A decision will soon reveal your true nature." },
  { quote: "A leaf reveals the unspoken promise.", reading: "You have been avoiding change everything." },
  { quote: "The river forgets the quiet growth.", reading: "Your strength is reveal your true nature." },
  { quote: "The wheel carries the clear vision.", reading: "An unexpected turn restore your balance." },
  { quote: "The root observes the path forward.", reading: "A quiet moment bring long awaited clarity." },
  { quote: "The sun hides the shifting light.", reading: "A familiar face test your patience." },
  { quote: "The forest carries the final answer.", reading: "The timing is provide the answer." },
  { quote: "A mirror reveals the weight of time.", reading: "The path you choose create a lasting impact." },
  { quote: "The sky seeks the weight of time.", reading: "The path you choose provide the answer." },
  { quote: "The root guides the unspoken promise.", reading: "The timing is offer a fresh start." },
  { quote: "The stone waits for the path forward.", reading: "The current phase restore your balance." },
  { quote: "The wheel tests the final answer.", reading: "A reunion will bring open a new door." },
  { quote: "The stone forgets the inner peace.", reading: "A familiar face restore your balance." },
  { quote: "The moon speaks to the distant future.", reading: "A discovery is near. offer a fresh start." },
  { quote: "A candle remembers the weight of time.", reading: "Your efforts are provide the answer." },
  { quote: "The river guides the silent truth.", reading: "The timing is offer a fresh start." },
  { quote: "The forest tests the shifting light.", reading: "Your strength is change everything." },
  { quote: "A seed seeks the secret joy.", reading: "A reunion will bring restore your balance." },
  { quote: "The wheel forgets the weight of time.", reading: "A discovery is near. lead to a unexpected success." },
  { quote: "A key breaks the shifting light.", reading: "A quiet moment provide the answer." },
  { quote: "A key forgets the quiet growth.", reading: "A discovery is near. challenge your beliefs." },
  { quote: "A key tests the hidden strength.", reading: "Your strength is test your patience." },
  { quote: "The wind breaks the inner peace.", reading: "An unexpected turn challenge your beliefs." },
  { quote: "A mirror holds the shifting light.", reading: "Your strength is redefine your priorities." },
  { quote: "The wind waits for the final answer.", reading: "Your efforts are provide the answer." },
  { quote: "The ocean hides the quiet growth.", reading: "Your strength is open a new door." },
  { quote: "The wind tests the weight of time.", reading: "A quiet moment offer a fresh start." },
  { quote: "A leaf shapes the rising tide.", reading: "Your strength is challenge your beliefs." },
  { quote: "The river hides the shifting light.", reading: "The current phase open a new door." },
  { quote: "The moon guides the clear vision.", reading: "A decision will soon provide the answer." },
  { quote: "A path guides the final answer.", reading: "The current phase open a new door." },
  { quote: "The wheel speaks to the heavy heart.", reading: "A reunion will bring open a new door." },
  { quote: "The sun hides the unspoken promise.", reading: "Your strength is open a new door." },
  { quote: "The fire carries the shifting light.", reading: "The current phase test your patience." },
  { quote: "The stone holds the distant future.", reading: "Your strength is redefine your priorities." },
  { quote: "A candle finds the inner peace.", reading: "Your strength is challenge your beliefs." },
  { quote: "A cloud breaks the silent truth.", reading: "A quiet moment test your patience." },
  { quote: "A seed observes the rising tide.", reading: "The current phase reveal your true nature." },
  { quote: "The shadow tests the quiet growth.", reading: "You have been avoiding offer a fresh start." },
  { quote: "A key guides the deep memory.", reading: "The current phase change everything." },
  { quote: "A candle remembers the deep memory.", reading: "The path you choose offer a fresh start." },
  { quote: "A key observes the final answer.", reading: "A quiet moment offer a fresh start." },
  { quote: "The wind hides the deep memory.", reading: "An unexpected turn redefine your priorities." },
  { quote: "The wheel finds the clear vision.", reading: "You have been avoiding challenge your beliefs." },
  { quote: "A leaf forgets the silent truth.", reading: "An unexpected turn redefine your priorities." },
  { quote: "A mirror breaks the path forward.", reading: "The path you choose offer a fresh start." },
  { quote: "The fire guides the heavy heart.", reading: "The timing is restore your balance." },
  { quote: "The sky remembers the inner peace.", reading: "Your strength is offer a fresh start." },
  { quote: "The sun observes the final answer.", reading: "You have been avoiding challenge your beliefs." },
  { quote: "A candle holds the clear vision.", reading: "An unexpected turn offer a fresh start." },
  { quote: "The stone remembers the deep memory.", reading: "The timing is offer a fresh start." },
  { quote: "The ocean waits for the silent truth.", reading: "The current phase redefine your priorities." },
  { quote: "A key reflects the silent truth.", reading: "An unexpected turn change everything." },
  { quote: "The river hides the inner peace.", reading: "The current phase open a new door." },
  { quote: "A seed hides the passing storm.", reading: "A familiar face provide the answer." },
  { quote: "A candle observes the unspoken promise.", reading: "A familiar face lead to a unexpected success." },
  { quote: "A bird carries the weight of time.", reading: "The current phase open a new door." },
  { quote: "A bridge reflects the secret joy.", reading: "A discovery is near. test your patience." },
  { quote: "The forest waits for the distant future.", reading: "The path you choose restore your balance." },
  { quote: "A star holds the silent truth.", reading: "A decision will soon create a lasting impact." },
  { quote: "The fire finds the rising tide.", reading: "A reunion will bring change everything." },
  { quote: "The ocean speaks to the secret joy.", reading: "Your efforts are lead to a unexpected success." },
  { quote: "The stone remembers the heavy heart.", reading: "The current phase challenge your beliefs." },
  { quote: "The moon seeks the path forward.", reading: "A quiet moment bring long awaited clarity." },
  { quote: "The fire reveals the hidden strength.", reading: "The path you choose test your patience." },
  { quote: "The sky guides the weight of time.", reading: "The path you choose challenge your beliefs." },
  { quote: "The forest remembers the path forward.", reading: "You have been avoiding reveal your true nature." },
  { quote: "A mountain hides the deep memory.", reading: "A familiar face offer a fresh start." },
  { quote: "The sun hides the shifting light.", reading: "An unexpected turn bring long awaited clarity." },
  { quote: "A mirror guides the heavy heart.", reading: "An unexpected turn challenge your beliefs." },
  { quote: "The ocean speaks to the heavy heart.", reading: "An unexpected turn reveal your true nature." },
  { quote: "The stone finds the silent truth.", reading: "Your strength is lead to a unexpected success." },
  { quote: "A gate reveals the quiet growth.", reading: "You have been avoiding offer a fresh start." },
  { quote: "The river carries the quiet growth.", reading: "A quiet moment reveal your true nature." },
  { quote: "A mirror seeks the inner peace.", reading: "Your strength is offer a fresh start." },
  { quote: "A path tests the unspoken promise.", reading: "Your efforts are restore your balance." },
  { quote: "A mirror finds the inner peace.", reading: "The current phase provide the answer." },
  { quote: "The sun reveals the silent truth.", reading: "A decision will soon change everything." },
  { quote: "The ocean carries the path forward.", reading: "The timing is redefine your priorities." },
  { quote: "The sky guides the unspoken promise.", reading: "A familiar face challenge your beliefs." },
  { quote: "A seed reflects the silent truth.", reading: "A quiet moment restore your balance." },
  { quote: "The sky breaks the heavy heart.", reading: "A quiet moment redefine your priorities." },
  { quote: "A leaf guides the deep memory.", reading: "A decision will soon redefine your priorities." },
  { quote: "A bird carries the passing storm.", reading: "An unexpected turn open a new door." },
  { quote: "The moon seeks the unspoken promise.", reading: "A quiet moment test your patience." },
  { quote: "The river reveals the final answer.", reading: "A decision will soon bring long awaited clarity." },
  { quote: "The river shapes the heavy heart.", reading: "You have been avoiding change everything." },
  { quote: "The wheel speaks to the heavy heart.", reading: "You have been avoiding challenge your beliefs." },
  { quote: "The sun seeks the weight of time.", reading: "The timing is test your patience." },
  { quote: "A bird waits for the weight of time.", reading: "The path you choose offer a fresh start." },
  { quote: "A cloud hides the clear vision.", reading: "The current phase restore your balance." },
  { quote: "A star reveals the quiet growth.", reading: "The timing is create a lasting impact." },
  { quote: "A bird remembers the silent truth.", reading: "The path you choose lead to a unexpected success." },
  { quote: "A bird carries the silent truth.", reading: "A familiar face change everything." },
  { quote: "The shadow shapes the clear vision.", reading: "The path you choose test your patience." },
  { quote: "A cloud waits for the inner peace.", reading: "You have been avoiding lead to a unexpected success." },
  { quote: "The shadow reveals the shifting light.", reading: "A quiet moment provide the answer." },
  { quote: "A cloud observes the path forward.", reading: "A decision will soon provide the answer." },
  { quote: "The ocean finds the unspoken promise.", reading: "A quiet moment offer a fresh start." },
  { quote: "The river guides the hidden strength.", reading: "An unexpected turn open a new door." },
  { quote: "The ocean shapes the silent truth.", reading: "The path you choose restore your balance." },
  { quote: "The sky forgets the path forward.", reading: "Your efforts are offer a fresh start." },
  { quote: "A mountain remembers the quiet growth.", reading: "A familiar face open a new door." },
  { quote: "A candle breaks the shifting light.", reading: "An unexpected turn bring long awaited clarity." },
  { quote: "A seed forgets the distant future.", reading: "A quiet moment lead to a unexpected success." },
  { quote: "The stone reflects the path forward.", reading: "A familiar face test your patience." },
  { quote: "A path seeks the distant future.", reading: "You have been avoiding test your patience." },
  { quote: "The fire guides the heavy heart.", reading: "A quiet moment reveal your true nature." },
  { quote: "The forest guides the quiet growth.", reading: "Your efforts are redefine your priorities." },
  { quote: "The shadow remembers the passing storm.", reading: "A discovery is near. restore your balance." },
  { quote: "A cloud observes the silent truth.", reading: "A familiar face create a lasting impact." },
  { quote: "The river speaks to the shifting light.", reading: "You have been avoiding lead to a unexpected success." },
  { quote: "The sun tests the inner peace.", reading: "The current phase open a new door." },
  { quote: "The root reveals the distant future.", reading: "Your efforts are redefine your priorities." },
  { quote: "The stone finds the final answer.", reading: "A reunion will bring lead to a unexpected success." },
  { quote: "A bridge seeks the deep memory.", reading: "The current phase lead to a unexpected success." },
  { quote: "A cloud observes the distant future.", reading: "A reunion will bring reveal your true nature." },
  { quote: "A gate speaks to the secret joy.", reading: "The current phase redefine your priorities." },
  { quote: "The root tests the distant future.", reading: "The current phase open a new door." },
  { quote: "The stone finds the final answer.", reading: "A familiar face redefine your priorities." },
  { quote: "A bridge seeks the silent truth.", reading: "A decision will soon test your patience." },
  { quote: "A gate finds the clear vision.", reading: "The path you choose lead to a unexpected success." },
  { quote: "The wind carries the rising tide.", reading: "A decision will soon restore your balance." },
  { quote: "The fire remembers the shifting light.", reading: "A quiet moment reveal your true nature." },
  { quote: "A leaf breaks the heavy heart.", reading: "A decision will soon test your patience." },
  { quote: "The ocean breaks the silent truth.", reading: "A quiet moment restore your balance." },
  { quote: "The root tests the distant future.", reading: "The path you choose lead to a unexpected success." },
  { quote: "A gate observes the rising tide.", reading: "A decision will soon restore your balance." },
  { quote: "The wheel carries the final answer.", reading: "You have been avoiding restore your balance." },
  { quote: "A star observes the passing storm.", reading: "An unexpected turn lead to a unexpected success." },
  { quote: "A leaf carries the silent truth.", reading: "A discovery is near. challenge your beliefs." },
  { quote: "A cloud observes the final answer.", reading: "Your strength is challenge your beliefs." },
  { quote: "A bird tests the unspoken promise.", reading: "A reunion will bring offer a fresh start." },
  { quote: "A mirror observes the heavy heart.", reading: "A reunion will bring change everything." },
  { quote: "A candle forgets the weight of time.", reading: "You have been avoiding lead to a unexpected success." },
  { quote: "The sun forgets the shifting light.", reading: "A familiar face provide the answer." },
  { quote: "The root observes the distant future.", reading: "You have been avoiding redefine your priorities." },
  { quote: "The sky breaks the quiet growth.", reading: "The current phase lead to a unexpected success." },
  { quote: "A path breaks the inner peace.", reading: "The timing is restore your balance." },
  { quote: "A mirror finds the rising tide.", reading: "An unexpected turn offer a fresh start." },
  { quote: "A mountain holds the unspoken promise.", reading: "A familiar face lead to a unexpected success." },
  { quote: "A mountain remembers the heavy heart.", reading: "A decision will soon restore your balance." },
  { quote: "A cloud speaks to the heavy heart.", reading: "Your efforts are redefine your priorities." },
  { quote: "The forest seeks the unspoken promise.", reading: "The path you choose offer a fresh start." },
  { quote: "A seed waits for the heavy heart.", reading: "Your efforts are create a lasting impact." },
  { quote: "A mountain hides the weight of time.", reading: "Your efforts are provide the answer." },
  { quote: "The sky remembers the unspoken promise.", reading: "A reunion will bring offer a fresh start." },
  { quote: "The ocean breaks the distant future.", reading: "The path you choose challenge your beliefs." },
  { quote: "The forest shapes the passing storm.", reading: "A familiar face create a lasting impact." },
  { quote: "The shadow guides the quiet growth.", reading: "A quiet moment redefine your priorities." },
  { quote: "The river reveals the shifting light.", reading: "Your strength is provide the answer." },
  { quote: "A bridge holds the clear vision.", reading: "The timing is challenge your beliefs." },
  { quote: "The shadow shapes the unspoken promise.", reading: "Your strength is open a new door." },
  { quote: "A key waits for the heavy heart.", reading: "The path you choose provide the answer." },
  { quote: "The sun observes the hidden strength.", reading: "A quiet moment create a lasting impact." },
  { quote: "The root reveals the inner peace.", reading: "Your strength is bring long awaited clarity." },
  { quote: "The river reveals the unspoken promise.", reading: "An unexpected turn reveal your true nature." },
  { quote: "A mountain breaks the heavy heart.", reading: "The current phase open a new door." },
  { quote: "A cloud shapes the heavy heart.", reading: "The timing is create a lasting impact." },
  { quote: "The fire reveals the distant future.", reading: "The path you choose change everything." },
  { quote: "The wind seeks the hidden strength.", reading: "A decision will soon challenge your beliefs." },
  { quote: "The fire speaks to the heavy heart.", reading: "The timing is provide the answer." },
  { quote: "The stone reflects the path forward.", reading: "An unexpected turn test your patience." },
  { quote: "A cloud breaks the secret joy.", reading: "An unexpected turn challenge your beliefs." },
  { quote: "A bridge remembers the silent truth.", reading: "The timing is open a new door." },
  { quote: "The moon guides the path forward.", reading: "A discovery is near. restore your balance." },
  { quote: "The wind guides the distant future.", reading: "Your strength is change everything." },
  { quote: "The river carries the passing storm.", reading: "A discovery is near. change everything." },
  { quote: "The ocean observes the silent truth.", reading: "The timing is restore your balance." },
  { quote: "A bridge reveals the path forward.", reading: "A decision will soon restore your balance." },
  { quote: "The sun seeks the heavy heart.", reading: "Your strength is bring long awaited clarity." },
  { quote: "The wheel waits for the clear vision.", reading: "You have been avoiding provide the answer." },
  { quote: "A star forgets the hidden strength.", reading: "A familiar face challenge your beliefs." }
];
